#!/bin/bash

echo "╔════════════════════════════════════════════════════════╗"
echo "║  Universal E-Paper Display Scanner v2.0                ║"
echo "║  Comprehensive Controller Detection Tool               ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "This advanced scanner detects 30+ e-paper controllers:"
echo ""
echo "Solomon Systech Family:"
echo "  • SSD1680 (2.13\" B/W)"
echo "  • SSD1681 (1.54\", 2.13\")"
echo "  • SSD1608 (2.0\" B/W)"
echo "  • SSD1606 (1.54\" B/W)"
echo "  • SSD1675 (2.7\" 3-color)"
echo "  • SSD1619 (2.0\" 3-color)"
echo ""
echo "Ultra Chip Family:"
echo "  • UC8151D (2.9\", 4.2\" 3-color)"
echo "  • UC8151C (2.13\" 3-color)"
echo "  • UC8253 (3.7\" 3-color)"
echo "  • UC8176 (4.2\"+ large displays)"
echo "  • UC8179 (7.5\"+ large displays)"
echo ""
echo "E Ink / ImagTek Family:"
echo "  • IL0373 (2.7\" 3-color)"
echo "  • IL0371 (1.54\" 3-color)"
echo "  • IL0398 (4.2\" 3-color)"
echo "  • IL3820 (1.54\" B/W)"
echo "  • IL3897 (5.83\" 3-color)"
echo ""
echo "Good Display / JD Chip:"
echo "  • GDEW series"
echo "  • JD796xx series"
echo ""
echo "════════════════════════════════════════════════════════"
echo ""
echo "Detection Methods:"
echo "  ✓ BUSY pin behavior analysis"
echo "  ✓ Command response testing"
echo "  ✓ Register read verification"
echo "  ✓ Controller signature matching"
echo "  ✓ Resolution detection"
echo "  ✓ Color RAM detection (B/W vs 3-color)"
echo ""
echo "════════════════════════════════════════════════════════"
echo ""

# Backup original main.c
if [ -f src/main.c ]; then
    echo "Backing up main.c..."
    cp src/main.c src/main_backup.c
fi

# Copy universal scanner to main.c
echo "Using universal scanner..."
cp src/main_universal_scanner.c src/main.c

# Build
echo "Building application..."
west build -b nrf52840dk/nrf52840 -- -DCONF_FILE=prj.conf -DDTC_OVERLAY_FILE=nrf52840dk_epd213_weact.overlay

echo ""
echo "════════════════════════════════════════════════════════"
echo "Build complete!"
echo ""
echo "To flash:"
echo "  west flash"
echo ""
echo "To monitor:"
echo "  screen /dev/ttyACM0 115200"
echo "  or"
echo "  minicom -D /dev/ttyACM0 -b 115200"
echo ""
echo "The scanner will run 8 comprehensive tests:"
echo "  1. BUSY pin behavior analysis"
echo "  2. Command response analysis"
echo "  3. Register read test"
echo "  4. Resolution detection"
echo "  5. Color RAM detection"
echo "  6. SSD1680 signature test"
echo "  7. UC8151D signature test"
echo "  8. IL0373 signature test"
echo ""
echo "Results include:"
echo "  • Controller name with confidence level"
echo "  • Detection method used"
echo "  • Color support (B/W or 3-color)"
echo "  • Manufacturer and specifications"
echo "  • Recommended driver settings"
echo "════════════════════════════════════════════════════════"
